src/config/routes.rb
Rails.application.routes.draw do
  resources :tprs
  devise_for :users
  #devise_for :users, skip: :recoverable
  # devise_for :users, except: "devise/passwords#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  #仮のルートパス
  #root "interims#index"

  root "pub_users#index"

  #一般ユーザー用のルーティング
  get '/pub_users/', to: 'pub_users#index', as: "pub_users"
  #こちらでもOK(全てのルーティングが出る)
  #resources :pub_users

  # Defines the root path route ("/")
  # root "posts#index"
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

src/app/models/tpr.rb
class Tpr < ApplicationRecord
  belongs_to :user
end

src/app/models/user.rb
class User < ApplicationRecord
  #Tprモデルの指定(Tprは多)
  has_many :tprs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         #パスワードのバリデーション最小文字を4文字最大を32にする
         #Deviseが提供するvalidatableモジュールにより、既にパスワードの最小・最大文字数の検証が行われているので不要
         #validates_length_of :encrypted_password, minimum: 4, maximum: 32

  #バリデーションメソッドでnameとemailに一意であることを宣言
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    #ストロングパラメーターの設定
    #新規登録(:sign_up)の時はデフォルトの値以外にnameとcompany_nameを受け付ける
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :company_name])
    end

    #after_sign_up_path_forを使って新規登録後にtprsに遷移する
    def after_sign_up_path_for(resource)
        tprs_path
    end

    #after_sign_in_path_forメソッドを使ってログイン後にtprsにリダイレクトさせる
    def after_sign_in_path_for(resource)
        tprs_path
    end

    #after_sign_out_path_forメソッドを使ってログアウトしたらtprsに戻す
    #ログインしていないとtprsには行けないのでサインアップ画面に遷移する
    def after_sign_out_path_for(resource)
        tprs_path
    end
end

src/app/controllers/interims_controller.rb
class InterimsController < ApplicationController
    def index
        @users = User.all()
    end
end

src/app/controllers/pub_users_controller.rb
#一般ユーザー用のコントローラーファイル
class PubUsersController < ApplicationController
    def index
        #Tprモデルのaverage_operating_raitoの平均値を取得
        avg = Tpr.average(:average_operating_raito)

        #今回はタクシーの台数を10000とする
        taxis = 10000

        #平均営業率(average_operating_raito)にタクシーの代数を掛けて
        #実際にお客様に対応できるタクシーの台数を計算
        taxis = avg * taxis

        #タクシーの利用を望むお客様の5%がタクシーでの移動を諦めたと仮定して
        #実際にお客様に対応できるタクシーの台数で対応できるお客様の数を算出
        #計算式(判別式)は煩雑なのでtaixsを100単位に値を増やし、対応できる
        #お客様の数をハッシュ化(実際のタクシー対応台数=>対応できるお客様の最大値)

        customers_hash = {
            5000 => 5157,5100 => 5258,5200 => 5359,5300 => 5461,5400 => 5562,
            5500 => 5663,5600 => 5765,5700 => 5865,5900 => 5966,5900 => 6068,
            6000 => 6169,6100 => 6270,6200 => 6371,6300 => 6472,6400 => 6573,
            6500 => 6674,6600 => 6775,6700 => 6876,6800 => 6977,6900 => 7078,
            7000 => 7179,7100 => 7280,7200 => 7381,7300 => 7482,7400 => 7583,
            7500 => 7684,7600 => 7785,7700 => 7886,7800 => 7981,7900 => 8088,
            8000 => 8189,8100 => 8290,8200 => 8390,8300 => 8592,8400 => 8693,
            8500 => 8801
        }

        @forcast = [taxis,customers_hash]
    end
end

src/app/controllers/tprs_controller.rb
class TprsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tpr, only: %i[ show edit update destroy ]

  # GET /tprs or /tprs.json
  def index
    @tprs = Tpr.all
  end

  # GET /tprs/1 or /tprs/1.json
  def show
  end

  # GET /tprs/new
  def new
    @tpr = Tpr.new
  end

  # GET /tprs/1/edit
  def edit
  end

  # POST /tprs or /tprs.json
  def create
    @tpr = Tpr.new(tpr_params)

    respond_to do |format|
      if @tpr.save
        format.html { redirect_to tpr_url(@tpr), notice: "Tpr was successfully created." }
        format.json { render :show, status: :created, location: @tpr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tpr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tprs/1 or /tprs/1.json
  def update
    respond_to do |format|
      if @tpr.update(tpr_params)
        format.html { redirect_to tpr_url(@tpr), notice: "Tpr was successfully updated." }
        format.json { render :show, status: :ok, location: @tpr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tpr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tprs/1 or /tprs/1.json
  def destroy
    @tpr.destroy!

    respond_to do |format|
      format.html { redirect_to tprs_url, notice: "Tpr was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tpr
      @tpr = Tpr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tpr_params
      params.require(:tpr).permit(:user_id, :business_time, :actual_driving, :pick_up_time, :waiting_time, :break_time, :backhaul_time, :average_operating_raito)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/tprs_helper.rb
module TprsHelper
end

src/app/views/interims/index.erb
<h1>仮のホーム画面です(削除可)</h1>

<div class="all-center">
  <p>ログイン仮</p>
  <%#<%= button_to 'ログイン',new_user_session_path, method: :get %>
  <%= button_to 'ログイン',new_user_session_path, method: :get %>
</div>

<div class="all-center">
  <p>新規登録仮</p>
  <%= button_to '新規登録',new_user_registration_path, method: :get %>
</div>

<div class="all-center">
  <p>ログアウト仮</p>
  <%= button_to 'ログアウト',destroy_user_session_path, method: :delete %>
</div>

<%# <script>//これは動いてないかも
  document.addEventListener("turbo:load", function() {
    const logoutForm = document.getElementById("logout-form");
    
    if (logoutForm) {
      logoutForm.addEventListener("submit", function() {
        // ボタンがクリックされた時の処理をここに追加（オプション）
      });
    }
  });
</script> %>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

src/app/views/pub_users/index.erb
<%# 一般ユーザーの画面 %>

<h1>ようこそ!タクシーつかまりやすいかな!?</h1>

<body>

<div id="content">
<%= form_tag pub_users_path, method: :get do %>
    <p class="all-center"><%= label_tag 'multiplier', '選択項目にチェックや選択をして下さい' %></p>

    <%# セレクトボックスの場合 %>

    <%# キーとバリューを合わせる時は一時配列 %>
    <%#<%= select_tag 'multiplier', options_for_select([[1,2,3,4,5]]) %>
    <%# キーとバリューを両方設定する時はoptions_for_select([['key1',val1],['key2',val2],...,['keyn',valn]])とする %>
    <%#<%= select_tag 'multiplier', options_for_select([['月曜朝または金曜23時~25時ですか?',1.18],['それ以外',1]]) %>

    <%# ラジオボタンの場合 %>
    <%# チェックボックスの場合 %>
    <%# <div class="all-center"> %>
    <dt>
        <p>日時:</p>
        <%= radio_button_tag 'multiplier1', 1.25 %>
        <%= label_tag 'multiplier1_1.25', '月曜朝または金曜23時~25時ですか?' %><br>

        <%= radio_button_tag 'multiplier1', 1.12 %>
        <%= label_tag 'multiplier1_1.12', '平日の火曜日~金曜日の朝ですか?' %><br>

        <%= radio_button_tag 'multiplier1', 0.8 %>
        <%= label_tag 'multiplier1_0.8', '土日祝祭日ですか?' %><br>

        <%= radio_button_tag 'multiplier1', 1 %>
        <%= label_tag 'multiplier1_1', 'それ以外ですか?' %><br>
    
        <p>気象条件:</p>
        <%= radio_button_tag 'multiplier2', 1.1 %>
        <%= label_tag 'multiplier2_1.1', '雨が降ってますか?' %><br>

        <%= radio_button_tag 'multiplier2', 1.45 %>
        <%= label_tag 'multiplier2_1.5', '台風である。または、雪が降ってますか?' %><br>

        <%= radio_button_tag 'multiplier2', 0.9 %>
        <%= label_tag 'multiplier2_0.9', '晴れていて気温が15~25°C位ですか?' %><br>

        <p>その他:</p>
        <%= check_box_tag 'multiplier3', 1.4 %>
        <%= label_tag 'multiplier3', '電車が止まってますか?' %><br>
    </dt>
    <%# 実際にお客様に対応できるタクシーの台数に近い値を@forcast[1]のキーから値を算出 %>
    <% key = @forcast[1].keys.min_by { |k| (k - @forcast[0]).abs } %>
    <% max_acceptation = @forcast[1][key] %>

    <% if params[:multiplier1].present? || params[:multiplier2].present? || params[:multiplier3].present? %>
        <%# max_accepationは@forcast[0]での最大輸送可能なお客様の数なので
        そこに外的要因の係数を掛けてお客様の需要予想数を算出 %>
        <%# デフォルト値がない場合 %>
        <%#<% result = @avg * params[:multiplier1].to_f * params[:multiplier2].to_f %>
        <%# デフォルト値がある場合はfetchメソッドを使う %>
        <% customers = max_acceptation * params.fetch(:multiplier1,1).to_f * params.fetch(:multiplier2,1).to_f * params.fetch(:multiplier3,1).to_f %>
    <% end %>

    
    <p class="all-center"><%= submit_tag '予想する' %></p>

    <h4>結果です</h4>

    <%# この値max_acceptationを基準にcustomerと比較して需要を予測 %>
    <div class="all-center">
        <% if (customers && customers >= max_acceptation - 255) && (customers && customers <= max_acceptation + 255) %>
            <p>空車のタクシーを見つけずらい状態です</p>
        <% elsif customers && customers < max_acceptation - 255 %>
            <p>空車のタクシーを見つけるのは容易です</p>
        <% elsif customers && customers > max_acceptation + 255 %>
            <p>空車タクシーを見つけるのは困難な状態です</p>
        <% else %>
            <p>予想します</p>
        <% end %>
    </div>

<% end %>
</div>
</body>

src/app/views/tprs/_form.html.erb
<%# new.html.erbやedit.html.erbのヘルパー %>
<%= form_with(model: tpr) do |form| %>
  <% if tpr.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tpr.errors.count, "error") %> prohibited this tpr from being saved:</h2>

      <ul>
        <% tpr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :business_time, style: "display: block" %>
    <%= form.text_field :business_time %>
  </div>

  <div>
    <%= form.label :actual_driving, style: "display: block" %>
    <%= form.text_field :actual_driving %>
  </div>

  <div>
    <%= form.label :pick_up_time, style: "display: block" %>
    <%= form.text_field :pick_up_time %>
  </div>

  <div>
    <%= form.label :waiting_time, style: "display: block" %>
    <%= form.text_field :waiting_time %>
  </div>

  <div>
    <%= form.label :break_time, style: "display: block" %>
    <%= form.text_field :break_time %>
  </div>

  <div>
    <%= form.label :backhaul_time, style: "display: block" %>
    <%= form.text_field :backhaul_time %>
  </div>

  <div>
    <%= form.label :average_operating_raito, style: "display: block" %>
    <%= form.text_field :average_operating_raito %>
  </div>

  <%# ここ編集 %>
  <br>

  <%# ここに確定するを追加 %>
  <div>
    <%= form.submit "確定する" %>
  </div>
<% end %>

src/app/views/tprs/_tpr.html.erb
<div id="<%= dom_id tpr %>">
  <p>
    <strong>User:</strong>
    <%= tpr.user_id %>
  </p>

  <p>
    <strong>Business time:</strong>
    <%= tpr.business_time %>
  </p>

  <p>
    <strong>Actual driving:</strong>
    <%= tpr.actual_driving %>
  </p>

  <p>
    <strong>Pick up time:</strong>
    <%= tpr.pick_up_time %>
  </p>

  <p>
    <strong>Waiting time:</strong>
    <%= tpr.waiting_time %>
  </p>

  <p>
    <strong>Break time:</strong>
    <%= tpr.break_time %>
  </p>

  <p>
    <strong>Backhaul time:</strong>
    <%= tpr.backhaul_time %>
  </p>

  <p>
    <strong>Average operating raito:</strong>
    <%= tpr.average_operating_raito %>
  </p>

</div>

src/app/views/tprs/edit.html.erb
<div class="all-center" >
  <h1>輸送実績の編集</h1>

  <%= render "form", tpr: @tpr %>

  <br>

  <div>
    <%= link_to "詳細に戻る", @tpr %> |
    <%= link_to "輸送実績一覧に戻る", tprs_path %>
  </div>
</div>

src/app/views/tprs/index.html.erb
<div class="all-center">
  <p style="color: green"><%= notice %></p>

  <h1>輸送実績報告書</h1>

  <%= button_to "新規データ入力", new_tpr_path, method: :get %><br>

  <%# deleteメソッドを使うときのデフォルトはこちら %>
  <%#<%= button_to 'ログアウト',destroy_user_session_path, method: :delete, form_class: 'link-caution-button2'%>
  
  <%# 1.へルパーメソッドbutton_to内ではclass属性を上手く指定できなかったのでbuttonタグで指定して
  2.jsのgetElementByIdを使ってdeleteメソッドを実行できるようにする %>
  <button class="link-caution-button2" onclick="submitForm()">ログアウト</button>

  <form id="logoutForm" action="<%= destroy_user_session_path %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </form><br>

  <p>===================================================</p>

  <div id="tprs">
    <% @tprs.each do |tpr| %>
      <%#<%= render tpr %>
      会社担当者ID:<%=  tpr.user_id%>  平均営業率:<%= tpr.average_operating_raito %>
      <p>
        <%= link_to "このデータの詳細", tpr %>
      <p>------------------------------------------------</p>
      </p>
    <% end %>
  </div>

  <script>
    function submitForm() {
      document.getElementById('logoutForm').submit();
    }
  </script>

</div>

src/app/views/tprs/new.html.erb
<h1>輸送実績報告の新規登録</h1>

<div class="all-center" >

  <%= render "form", tpr: @tpr %>

  <br>

  <div>
    <%= link_to "輸送実績一覧に戻る", tprs_path %>
  </div>
</div>

src/app/views/tprs/show.html.erb
<div class="all-center">
  <p style="color: green"><%= notice %></p>
  <h1>詳細画面</h1>
  <%# 日本語化する為scafflodで作られた直接属性名をやめて
  i18n.tメソッドを使用して翻訳キーを指定してtpr.ja.ymlを呼び出す %>

  <%# 上の方法で呼び出せなかったのでconfig/locales/ja.ymlにtメソッドを
  使って呼び出す方法に変更 %>

  <%#<%= render @tpr %>

  <%# tメソッドを使ってja.ymlのtprs/showを呼び出す %>
  <div>
    <%= t('.user_id') %>: <%= @tpr.user_id %>
  </div><br>

  <div>
    <%= t('.business_time') %>: <%= @tpr.business_time %>
  </div><br>

  <div>
    <%= t('.actual_driving') %>: <%= @tpr.actual_driving %>
  </div><br>

  <div>
    <%= t('.pick_up_time') %>: <%= @tpr.pick_up_time %>
  </div><br>

  <div>
    <%= t('.waiting_time') %>: <%= @tpr.waiting_time %>
  </div><br>

  <div>
    <%= t('.break_time') %>: <%= @tpr.break_time %>
  </div><br>

  <div>
    <%= t('.backhaul_time') %>: <%= @tpr.backhaul_time %>
  </div><br>

  <div>
    <%= t('.average_operating_raito') %>: <%= @tpr.average_operating_raito %>
  </div><br>

  <p>
    <%= link_to "編集する", edit_tpr_path(@tpr) %> |
    <%= link_to "輸送実績一覧に戻る", tprs_path %>
  </p>

  <%#<%= button_to "このデータを削除する", @tpr, method: :delete %>

  <button class="link-delete-button2" onclick="submitForm()">このデータを削除する</button>

  <form id="logoutForm" action="<%= @tpr %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </form><br>

  <script>
    function submitForm() {
      document.getElementById('logoutForm').submit();
    }
  </script>

</div>

src/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

src/app/views/users/shared/_links.html.erb
<%# リンクの表示を条件によって変化させるためのヘルパー %>
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%# 今回は使わ無いのでコメントアウト %>
<%#<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#<%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%#<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>